version: '3.5'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db_service:
        condition: service_healthy
      nats:
        condition: service_started
      

  db_service:
    container_name: db_service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 10s
      retries: 5

  nats:
    image: nats-streaming:0.25.6
    command: ["-p", "4222", "--cluster_id", "test-cluster"]
    ports:
      - "4222:4222"
    restart: always